GeorgesMovies/GeorgesMovies.Web/Controllers/ActorController.cs
using System.Linq;
using GeorgesMovies.Services.Actors;
using GeorgesMovies.Services.Actors.DTO;
using GeorgesMovies.Web.Models.Actors;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static GeorgesMovies.Web.WebConstants;
using static GeorgesMovies.Web.Areas.Admin.AdminAreaConstants;


namespace GeorgesMovies.Web.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorService actors;

        public ActorController(IActorService actors)
        {
            this.actors = actors;
        }

        [Authorize(Roles = AdminRoleName)]
        public IActionResult Add()
        {
            return View(new AddActorServiceModel
            {
                Movies = this.actors.GetMoviesTitles()
            });
        }

        [Authorize(Roles = AdminRoleName)]
        [HttpPost]
        public IActionResult Add(AddActorServiceModel actorToAdd)
        {
            var isActorInData = this.actors.ExistActorInMovie(actorToAdd);

            if (isActorInData)
            {
                this.ModelState.AddModelError(nameof(actorToAdd.FirstName), "This actor is already in movie");
            }
            if (!ModelState.IsValid)
            {
                return View(new AddActorServiceModel
                {
                    Movies = this.actors.GetMoviesTitles()
                });
            }
            this.actors.Add(actorToAdd);

            return RedirectToAction("Manage", "Movie",new { area = AreaName});
        }

        [Authorize]
        public IActionResult All()
        {
            var actors = new AllActorsViewModel
            {
                Actors = this.actors.GetAllActorsNames().ToList()
            };

            return View(actors);
        }

        [Authorize]
        public IActionResult Info(int id)
        {
            var infoForActor = this.actors.GetInfoAboutActor(id);

            return View(infoForActor);
        }
    }
}

GeorgesMovies/GeorgesMovies.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using GeorgesMovies.Models.Models;
@using GeorgesMovies.Web.Areas.Admin;
@inject UserManager<User> UserManager


@{ 
    var usersCount = this.UserManager.Users.Count();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeorgesMovies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area=" " asp-controller="Home" asp-action="Index">GeorgesMovies</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User.IsInRole(WebConstants.AdminRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="@(AdminAreaConstants.AreaName)" asp-controller="Movie" asp-action="Manage" >Manage</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark"asp-area=""  asp-controller="Actor" asp-action="All">List of actors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="All">All movies</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <div class="mb-5"></div>

        </main>
    </div>
    <footer class="border-top footer text-muted mb-5">

        <div class="container">
            <div style="margin:auto" class="float-left">
                &copy; @DateTime.UtcNow.Year - GeorgesMovies
                <a style="margin:310px"
                   href="https://github.com/GeorgiPopovIT/GeorgesMovies">
                    Open Source Code
                </a>

            </div>
            <div class="float-right">
                Registered Users: @usersCount
            </div>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>